included:
    - Sources

# rule identifiers to exclude from running
disabled_rules:
    - cyclomatic_complexity
    - variable_name
    - type_name

shorthand_operator: warning
superfluous_disable_command: warning

# some rules are only opt-in
opt_in_rules:
    - empty_count

# configurable rules can be customized from this configuration file
line_length: 200
